### ISSUE TITLE
UI is missing from kotlinx coroutines 

### ISSUE THREAD

**Issue by ronnie173** [PacktPublishing/Kotlin-Standard-Library-Cookbook#1]
import kotlinx.coroutines.experimental.android.UI
is missing and need to know what else to use in it's place

**Comment by samiuelson** [comment]
@ronnie173 could you provide more details about your problem?
The `UI` is available as a field of `HandlerContext` class: https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/kotlinx-coroutines-android/src/HandlerContext.kt
To use it in your project you should add the following declaration to your module-level `build.gradle` file: `implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:0.22.2'`

Let me know if you have further problems using it.

**Comment by samiuelson** [comment]
I'm closing the issue. @ronnie173 feel free to reopen if you still have any issues 👍
